# Generated by Django 4.1 on 2022-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_brands_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='raiting',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
