# Generated by Django 4.1 on 2022-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_alter_products_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='raiting',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
