# Generated by Django 4.1 on 2022-09-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_products_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='details',
        ),
        migrations.CreateModel(
            name='ProductsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=50)),
                ('detail_value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productDetails', to='category.products')),
            ],
        ),
    ]
