# Generated by Django 4.1 on 2022-09-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_remove_products_details_productsdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='raiting',
        ),
        migrations.CreateModel(
            name='ProductRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRaiting', to='category.products')),
            ],
        ),
    ]
