# Generated by Django 4.1 on 2022-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productraiting',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
