# Generated by Django 4.1 on 2022-08-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(related_name='brands', to='category.brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='category.brands'),
        ),
    ]
