# Generated by Django 4.1 on 2022-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_products_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='raiting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
