# Generated by Django 4.1 on 2022-09-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_remove_products_image_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
