# Generated by Django 4.1 on 2022-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_alter_products_price'),
        ('home', '0004_alter_claim_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='products',
            field=models.ManyToManyField(related_name='delas', to='category.products'),
        ),
    ]
