# Generated by Django 4.1 on 2022-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Claim')),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
