# Generated by Django 4.1 on 2022-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_claim_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='deal_choices',
            field=models.CharField(choices=[('subtraction', 'subtraction'), ('percent', 'percent')], default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='deal_sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
